# GitHub Actions workflow for Dependabot configuration

version: 2
updates:
  # Enable version updates for pip

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "automated"
      - "github-actions"
