name: Update Docker Images (Shared Action)

on:
  push:
    branches: ["main"]
    paths:
      - "**/*.py"
      - "**/*.html"
      - "package.json"
      - "package-lock.json"
      - "requirements.txt"
      - "Dockerfile"
      - "Pipfile"
      - "Pipfile.lock"
      - ".github/"
      - ".github/**"
      - ".dockerignore"
      - "**.*.style"

  workflow_dispatch:
  schedule: # 2 AM on Monday
    - cron: "0 2 * * 1"

permissions:
  contents: write
  # workflows: write
  actions: write

jobs:
  docker-publish:
    uses: charl3y15/reusable-actions/.github/workflows/docker-publish-python.yml@main
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      GH_USERNAME: ${{ secrets.GH_USERNAME }}
      GH_ORG: ${{ secrets.GH_ORG }}
