name: auto-merge

on:
  pull_request:
  workflow_call:
    secrets:
      GH_PAT:
        required: true
      GH_USERNAME:
        required: true
      GH_ORG:
        required: true

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.3.0
      - uses: ahmadnassri/action-dependabot-auto-merge@v2.6.6
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          command: "merge"
          approve: true
