name: Lint Python
on:
  push:
  pull_request:
  workflow_call:
    secrets:
      GH_PAT:
        required: true
      GH_USERNAME:
        required: true
      GH_ORG:
        required: true

jobs:
  python-black:
    name: Python Black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Python Black
        uses: cytopia/docker-black@0.11
    #    with:
    #    path: 'src/'
